set number	    " Show line numbers
set mouse=a	    " Enable inaction via mouse
set showmatch	    " Highlight matching brace
set cursorline	    " Show underline
set cursorcolumn    " Show vertical column highlight
set ruler	    " Show row and column ruler information

filetype on	"enable file detection
syntax on	"syntax highlight
 
set autoindent	    " Auto-indent new lines
set shiftwidth=4    " Number of auto-indent spaces
set smartindent	    " Enable smart-indent
set smarttab	    " Enable smart-tabs
set softtabstop=4   " Number of spaces per Tab

" ---------Optional----------

set undolevels=10000	" Number of undo levels
set scrolloff=5		"auto scroll on the bottom 5 lines
 
set hlsearch	    " Highlight all search results
set smartcase	    " Enable smart-case search
set ignorecase	    " Always case-insensitive
set incsearch	    " Searches for strings incrementally

highlight Comment ctermfg=cyan
set showmode

set encoding=utf-8
set fileencoding=utf-8
scriptencoding=utf-8

